// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: detector.proto

package detector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Detector_Detect_FullMethodName = "/rvo.detect.v1.Detector/Detect"
)

// DetectorClient is the client API for Detector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A model service implements Detector: it receives a single encoded frame and
// returns zero or more typed signals. This is the contract RVO uses to fan
// frames out to external (e.g. Python) inference services.
type DetectorClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type detectorClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorClient(cc grpc.ClientConnInterface) DetectorClient {
	return &detectorClient{cc}
}

func (c *detectorClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, Detector_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectorServer is the server API for Detector service.
// All implementations must embed UnimplementedDetectorServer
// for forward compatibility.
//
// A model service implements Detector: it receives a single encoded frame and
// returns zero or more typed signals. This is the contract RVO uses to fan
// frames out to external (e.g. Python) inference services.
type DetectorServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	mustEmbedUnimplementedDetectorServer()
}

// UnimplementedDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectorServer struct{}

func (UnimplementedDetectorServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectorServer) mustEmbedUnimplementedDetectorServer() {}
func (UnimplementedDetectorServer) testEmbeddedByValue()                  {}

// UnsafeDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectorServer will
// result in compilation errors.
type UnsafeDetectorServer interface {
	mustEmbedUnimplementedDetectorServer()
}

func RegisterDetectorServer(s grpc.ServiceRegistrar, srv DetectorServer) {
	// If the following call panics, it indicates UnimplementedDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Detector_ServiceDesc, srv)
}

func _Detector_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Detector_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Detector_ServiceDesc is the grpc.ServiceDesc for Detector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Detector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rvo.detect.v1.Detector",
	HandlerType: (*DetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _Detector_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detector.proto",
}
