// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: detector.proto

package detector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JPEG-encoded frame bytes (encoded by the RVO-side worker via OpenCV).
	FrameJpeg []byte `protobuf:"bytes,1,opt,name=frame_jpeg,json=frameJpeg,proto3" json:"frame_jpeg,omitempty"`
	// Monotonic frame id from the camera, for logging/correlation.
	FrameId uint64 `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Optional capture timestamp in nanoseconds (0 if unknown).
	TsNs          uint64 `protobuf:"varint,3,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_detector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{0}
}

func (x *DetectRequest) GetFrameJpeg() []byte {
	if x != nil {
		return x.FrameJpeg
	}
	return nil
}

func (x *DetectRequest) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *DetectRequest) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

type DetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*SignalOut           `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_detector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{1}
}

func (x *DetectResponse) GetSignals() []*SignalOut {
	if x != nil {
		return x.Signals
	}
	return nil
}

type SignalOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match an RVO SignalType name: "Dummy" | "MotionLevel" |
	// "FacePresent" | "PersonDetected".
	SignalType string `protobuf:"bytes,1,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	// Signal payload (e.g. 1 = present, or a normalised score 0..255).
	Value uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	// Suggested freshness window in nanoseconds (advisory; RVO also applies its
	// own TTL based on result age).
	TtlNs         uint64 `protobuf:"varint,3,opt,name=ttl_ns,json=ttlNs,proto3" json:"ttl_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalOut) Reset() {
	*x = SignalOut{}
	mi := &file_detector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalOut) ProtoMessage() {}

func (x *SignalOut) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalOut.ProtoReflect.Descriptor instead.
func (*SignalOut) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{2}
}

func (x *SignalOut) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SignalOut) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SignalOut) GetTtlNs() uint64 {
	if x != nil {
		return x.TtlNs
	}
	return 0
}

var File_detector_proto protoreflect.FileDescriptor

const file_detector_proto_rawDesc = "" +
	"\n" +
	"\x0edetector.proto\x12\rrvo.detect.v1\"^\n" +
	"\rDetectRequest\x12\x1d\n" +
	"\n" +
	"frame_jpeg\x18\x01 \x01(\fR\tframeJpeg\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x04R\aframeId\x12\x13\n" +
	"\x05ts_ns\x18\x03 \x01(\x04R\x04tsNs\"D\n" +
	"\x0eDetectResponse\x122\n" +
	"\asignals\x18\x01 \x03(\v2\x18.rvo.detect.v1.SignalOutR\asignals\"Y\n" +
	"\tSignalOut\x12\x1f\n" +
	"\vsignal_type\x18\x01 \x01(\tR\n" +
	"signalType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\x12\x15\n" +
	"\x06ttl_ns\x18\x03 \x01(\x04R\x05ttlNs2Q\n" +
	"\bDetector\x12E\n" +
	"\x06Detect\x12\x1c.rvo.detect.v1.DetectRequest\x1a\x1d.rvo.detect.v1.DetectResponseBIZGgithub.com/kushagrathisside/RealTime-Video-Orchestrator/sdk/go;detectorb\x06proto3"

var (
	file_detector_proto_rawDescOnce sync.Once
	file_detector_proto_rawDescData []byte
)

func file_detector_proto_rawDescGZIP() []byte {
	file_detector_proto_rawDescOnce.Do(func() {
		file_detector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detector_proto_rawDesc), len(file_detector_proto_rawDesc)))
	})
	return file_detector_proto_rawDescData
}

var file_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_detector_proto_goTypes = []any{
	(*DetectRequest)(nil),  // 0: rvo.detect.v1.DetectRequest
	(*DetectResponse)(nil), // 1: rvo.detect.v1.DetectResponse
	(*SignalOut)(nil),      // 2: rvo.detect.v1.SignalOut
}
var file_detector_proto_depIdxs = []int32{
	2, // 0: rvo.detect.v1.DetectResponse.signals:type_name -> rvo.detect.v1.SignalOut
	0, // 1: rvo.detect.v1.Detector.Detect:input_type -> rvo.detect.v1.DetectRequest
	1, // 2: rvo.detect.v1.Detector.Detect:output_type -> rvo.detect.v1.DetectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_detector_proto_init() }
func file_detector_proto_init() {
	if File_detector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detector_proto_rawDesc), len(file_detector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detector_proto_goTypes,
		DependencyIndexes: file_detector_proto_depIdxs,
		MessageInfos:      file_detector_proto_msgTypes,
	}.Build()
	File_detector_proto = out.File
	file_detector_proto_goTypes = nil
	file_detector_proto_depIdxs = nil
}
