// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: detector.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "rvo.detect.v1";

export interface DetectRequest {
  /** JPEG-encoded frame bytes (encoded by the RVO-side worker via OpenCV). */
  frameJpeg: Buffer;
  /** Monotonic frame id from the camera, for logging/correlation. */
  frameId: number;
  /** Optional capture timestamp in nanoseconds (0 if unknown). */
  tsNs: number;
}

export interface DetectResponse {
  signals: SignalOut[];
}

export interface SignalOut {
  /**
   * Must match an RVO SignalType name: "Dummy" | "MotionLevel" |
   * "FacePresent" | "PersonDetected".
   */
  signalType: string;
  /** Signal payload (e.g. 1 = present, or a normalised score 0..255). */
  value: number;
  /**
   * Suggested freshness window in nanoseconds (advisory; RVO also applies its
   * own TTL based on result age).
   */
  ttlNs: number;
}

function createBaseDetectRequest(): DetectRequest {
  return { frameJpeg: Buffer.alloc(0), frameId: 0, tsNs: 0 };
}

export const DetectRequest: MessageFns<DetectRequest> = {
  encode(message: DetectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameJpeg.length !== 0) {
      writer.uint32(10).bytes(message.frameJpeg);
    }
    if (message.frameId !== 0) {
      writer.uint32(16).uint64(message.frameId);
    }
    if (message.tsNs !== 0) {
      writer.uint32(24).uint64(message.tsNs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.frameJpeg = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.frameId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.tsNs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectRequest {
    return {
      frameJpeg: isSet(object.frameJpeg)
        ? Buffer.from(bytesFromBase64(object.frameJpeg))
        : isSet(object.frame_jpeg)
        ? Buffer.from(bytesFromBase64(object.frame_jpeg))
        : Buffer.alloc(0),
      frameId: isSet(object.frameId)
        ? globalThis.Number(object.frameId)
        : isSet(object.frame_id)
        ? globalThis.Number(object.frame_id)
        : 0,
      tsNs: isSet(object.tsNs)
        ? globalThis.Number(object.tsNs)
        : isSet(object.ts_ns)
        ? globalThis.Number(object.ts_ns)
        : 0,
    };
  },

  toJSON(message: DetectRequest): unknown {
    const obj: any = {};
    if (message.frameJpeg.length !== 0) {
      obj.frameJpeg = base64FromBytes(message.frameJpeg);
    }
    if (message.frameId !== 0) {
      obj.frameId = Math.round(message.frameId);
    }
    if (message.tsNs !== 0) {
      obj.tsNs = Math.round(message.tsNs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectRequest>, I>>(base?: I): DetectRequest {
    return DetectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectRequest>, I>>(object: I): DetectRequest {
    const message = createBaseDetectRequest();
    message.frameJpeg = object.frameJpeg ?? Buffer.alloc(0);
    message.frameId = object.frameId ?? 0;
    message.tsNs = object.tsNs ?? 0;
    return message;
  },
};

function createBaseDetectResponse(): DetectResponse {
  return { signals: [] };
}

export const DetectResponse: MessageFns<DetectResponse> = {
  encode(message: DetectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.signals) {
      SignalOut.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signals.push(SignalOut.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectResponse {
    return {
      signals: globalThis.Array.isArray(object?.signals) ? object.signals.map((e: any) => SignalOut.fromJSON(e)) : [],
    };
  },

  toJSON(message: DetectResponse): unknown {
    const obj: any = {};
    if (message.signals?.length) {
      obj.signals = message.signals.map((e) => SignalOut.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectResponse>, I>>(base?: I): DetectResponse {
    return DetectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectResponse>, I>>(object: I): DetectResponse {
    const message = createBaseDetectResponse();
    message.signals = object.signals?.map((e) => SignalOut.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSignalOut(): SignalOut {
  return { signalType: "", value: 0, ttlNs: 0 };
}

export const SignalOut: MessageFns<SignalOut> = {
  encode(message: SignalOut, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signalType !== "") {
      writer.uint32(10).string(message.signalType);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint64(message.value);
    }
    if (message.ttlNs !== 0) {
      writer.uint32(24).uint64(message.ttlNs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalOut {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalOut();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signalType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ttlNs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalOut {
    return {
      signalType: isSet(object.signalType)
        ? globalThis.String(object.signalType)
        : isSet(object.signal_type)
        ? globalThis.String(object.signal_type)
        : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      ttlNs: isSet(object.ttlNs)
        ? globalThis.Number(object.ttlNs)
        : isSet(object.ttl_ns)
        ? globalThis.Number(object.ttl_ns)
        : 0,
    };
  },

  toJSON(message: SignalOut): unknown {
    const obj: any = {};
    if (message.signalType !== "") {
      obj.signalType = message.signalType;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.ttlNs !== 0) {
      obj.ttlNs = Math.round(message.ttlNs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignalOut>, I>>(base?: I): SignalOut {
    return SignalOut.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalOut>, I>>(object: I): SignalOut {
    const message = createBaseSignalOut();
    message.signalType = object.signalType ?? "";
    message.value = object.value ?? 0;
    message.ttlNs = object.ttlNs ?? 0;
    return message;
  },
};

/**
 * A model service implements Detector: it receives a single encoded frame and
 * returns zero or more typed signals. This is the contract RVO uses to fan
 * frames out to external (e.g. Python) inference services.
 */
export type DetectorService = typeof DetectorService;
export const DetectorService = {
  detect: {
    path: "/rvo.detect.v1.Detector/Detect" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DetectRequest): Buffer => Buffer.from(DetectRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DetectRequest => DetectRequest.decode(value),
    responseSerialize: (value: DetectResponse): Buffer => Buffer.from(DetectResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DetectResponse => DetectResponse.decode(value),
  },
} as const;

export interface DetectorServer extends UntypedServiceImplementation {
  detect: handleUnaryCall<DetectRequest, DetectResponse>;
}

export interface DetectorClient extends Client {
  detect(
    request: DetectRequest,
    callback: (error: ServiceError | null, response: DetectResponse) => void,
  ): ClientUnaryCall;
  detect(
    request: DetectRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DetectResponse) => void,
  ): ClientUnaryCall;
  detect(
    request: DetectRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DetectResponse) => void,
  ): ClientUnaryCall;
}

export const DetectorClient = makeGenericClientConstructor(DetectorService, "rvo.detect.v1.Detector") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): DetectorClient;
  service: typeof DetectorService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
